/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.11.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QPushButton *pBVpp;
    QPushButton *pBfreq;
    QPushButton *pBond;
    QPushButton *pBdivX;
    QPushButton *pBdivY;
    QPushButton *pBopc;
    QCustomPlot *grafico;
    QSlider *SlVpp;
    QLabel *lbSlVpp;
    QSlider *Sloffset;
    QLabel *lbSloffset;
    QSlider *SlFreq;
    QLabel *lbSlFreq;
    QSlider *Sldivx;
    QLabel *lbSldivx;
    QLabel *lbSldivy;
    QSlider *Sldivy;
    QGroupBox *gbondas;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout;
    QPushButton *pBond_3;
    QPushButton *pBond_4;
    QPushButton *pBond_2;
    QPushButton *pBond_5;
    QLabel *label;
    QLabel *label_2;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(600, 480);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setToolTipDuration(-1);
        MainWindow->setStyleSheet(QStringLiteral("background-color: black"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(0, 431, 600, 4));
        line->setStyleSheet(QStringLiteral("color: white"));
        line->setFrameShadow(QFrame::Plain);
        line->setLineWidth(2);
        line->setFrameShape(QFrame::HLine);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(528, 433, 3, 49));
        line_4->setStyleSheet(QStringLiteral("color: white"));
        line_4->setFrameShadow(QFrame::Plain);
        line_4->setLineWidth(2);
        line_4->setFrameShape(QFrame::VLine);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(438, 433, 3, 49));
        line_5->setStyleSheet(QStringLiteral("color: white"));
        line_5->setFrameShadow(QFrame::Plain);
        line_5->setLineWidth(2);
        line_5->setFrameShape(QFrame::VLine);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(348, 433, 3, 49));
        line_6->setStyleSheet(QStringLiteral("color: white"));
        line_6->setFrameShadow(QFrame::Plain);
        line_6->setLineWidth(2);
        line_6->setFrameShape(QFrame::VLine);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(240, 433, 3, 49));
        line_7->setStyleSheet(QStringLiteral("color: white"));
        line_7->setFrameShadow(QFrame::Plain);
        line_7->setLineWidth(2);
        line_7->setFrameShape(QFrame::VLine);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(120, 433, 3, 49));
        line_8->setStyleSheet(QStringLiteral("color: white"));
        line_8->setFrameShadow(QFrame::Plain);
        line_8->setLineWidth(2);
        line_8->setFrameShape(QFrame::VLine);
        pBVpp = new QPushButton(centralWidget);
        pBVpp->setObjectName(QStringLiteral("pBVpp"));
        pBVpp->setGeometry(QRect(5, 436, 110, 41));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        palette.setBrush(QPalette::Active, QPalette::Window, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        QBrush brush2(QColor(190, 190, 190, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBVpp->setPalette(palette);
        pBVpp->setAutoFillBackground(false);
        pBVpp->setFlat(true);
        pBfreq = new QPushButton(centralWidget);
        pBfreq->setObjectName(QStringLiteral("pBfreq"));
        pBfreq->setGeometry(QRect(126, 436, 110, 41));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush3(QColor(238, 238, 236, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBfreq->setPalette(palette1);
        pBfreq->setAutoFillBackground(false);
        pBfreq->setFlat(true);
        pBond = new QPushButton(centralWidget);
        pBond->setObjectName(QStringLiteral("pBond"));
        pBond->setGeometry(QRect(250, 436, 91, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBond->setPalette(palette2);
        pBond->setAutoFillBackground(false);
        QIcon icon;
        icon.addFile(QStringLiteral(":/seno.png"), QSize(), QIcon::Normal, QIcon::Off);
        pBond->setIcon(icon);
        pBond->setIconSize(QSize(70, 60));
        pBond->setFlat(true);
        pBdivX = new QPushButton(centralWidget);
        pBdivX->setObjectName(QStringLiteral("pBdivX"));
        pBdivX->setGeometry(QRect(353, 436, 81, 41));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBdivX->setPalette(palette3);
        pBdivX->setAutoFillBackground(false);
        pBdivX->setFlat(true);
        pBdivY = new QPushButton(centralWidget);
        pBdivY->setObjectName(QStringLiteral("pBdivY"));
        pBdivY->setGeometry(QRect(444, 436, 81, 41));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBdivY->setPalette(palette4);
        pBdivY->setAutoFillBackground(false);
        pBdivY->setFlat(true);
        pBopc = new QPushButton(centralWidget);
        pBopc->setObjectName(QStringLiteral("pBopc"));
        pBopc->setGeometry(QRect(534, 436, 61, 41));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/opc.png"), QSize(), QIcon::Normal, QIcon::Off);
        pBopc->setIcon(icon1);
        pBopc->setIconSize(QSize(30, 30));
        pBopc->setFlat(true);
        grafico = new QCustomPlot(centralWidget);
        grafico->setObjectName(QStringLiteral("grafico"));
        grafico->setGeometry(QRect(1, 1, 598, 430));
        SlVpp = new QSlider(grafico);
        SlVpp->setObjectName(QStringLiteral("SlVpp"));
        SlVpp->setEnabled(true);
        SlVpp->setGeometry(QRect(20, 40, 20, 391));
        QPalette palette5;
        QBrush brush4(QColor(211, 215, 207, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush4);
        QBrush brush5(QColor(70, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        SlVpp->setPalette(palette5);
        SlVpp->setFocusPolicy(Qt::StrongFocus);
        SlVpp->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        SlVpp->setMaximum(60);
        SlVpp->setSingleStep(1);
        SlVpp->setPageStep(10);
        SlVpp->setValue(5);
        SlVpp->setSliderPosition(5);
        SlVpp->setOrientation(Qt::Vertical);
        SlVpp->setInvertedAppearance(false);
        SlVpp->setInvertedControls(false);
        SlVpp->setTickPosition(QSlider::NoTicks);
        lbSlVpp = new QLabel(grafico);
        lbSlVpp->setObjectName(QStringLiteral("lbSlVpp"));
        lbSlVpp->setGeometry(QRect(14, 15, 31, 21));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lbSlVpp->setPalette(palette6);
        Sloffset = new QSlider(grafico);
        Sloffset->setObjectName(QStringLiteral("Sloffset"));
        Sloffset->setEnabled(true);
        Sloffset->setGeometry(QRect(86, 40, 20, 391));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        Sloffset->setPalette(palette7);
        Sloffset->setFocusPolicy(Qt::StrongFocus);
        Sloffset->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        Sloffset->setMaximum(20);
        Sloffset->setSingleStep(1);
        Sloffset->setOrientation(Qt::Vertical);
        Sloffset->setInvertedAppearance(false);
        Sloffset->setInvertedControls(false);
        Sloffset->setTickPosition(QSlider::NoTicks);
        lbSloffset = new QLabel(grafico);
        lbSloffset->setObjectName(QStringLiteral("lbSloffset"));
        lbSloffset->setGeometry(QRect(70, 15, 51, 21));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lbSloffset->setPalette(palette8);
        SlFreq = new QSlider(grafico);
        SlFreq->setObjectName(QStringLiteral("SlFreq"));
        SlFreq->setEnabled(true);
        SlFreq->setGeometry(QRect(170, 40, 20, 391));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        SlFreq->setPalette(palette9);
        SlFreq->setFocusPolicy(Qt::StrongFocus);
        SlFreq->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        SlFreq->setMaximum(60);
        SlFreq->setSingleStep(1);
        SlFreq->setPageStep(10);
        SlFreq->setValue(5);
        SlFreq->setSliderPosition(5);
        SlFreq->setOrientation(Qt::Vertical);
        SlFreq->setInvertedAppearance(false);
        SlFreq->setInvertedControls(false);
        SlFreq->setTickPosition(QSlider::NoTicks);
        lbSlFreq = new QLabel(grafico);
        lbSlFreq->setObjectName(QStringLiteral("lbSlFreq"));
        lbSlFreq->setGeometry(QRect(140, 15, 81, 21));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lbSlFreq->setPalette(palette10);
        Sldivx = new QSlider(grafico);
        Sldivx->setObjectName(QStringLiteral("Sldivx"));
        Sldivx->setEnabled(true);
        Sldivx->setGeometry(QRect(386, 40, 20, 391));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        Sldivx->setPalette(palette11);
        Sldivx->setFocusPolicy(Qt::StrongFocus);
        Sldivx->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        Sldivx->setMaximum(60);
        Sldivx->setSingleStep(1);
        Sldivx->setPageStep(10);
        Sldivx->setValue(5);
        Sldivx->setSliderPosition(5);
        Sldivx->setOrientation(Qt::Vertical);
        Sldivx->setInvertedAppearance(false);
        Sldivx->setInvertedControls(false);
        Sldivx->setTickPosition(QSlider::NoTicks);
        lbSldivx = new QLabel(grafico);
        lbSldivx->setObjectName(QStringLiteral("lbSldivx"));
        lbSldivx->setGeometry(QRect(377, 15, 41, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lbSldivx->setPalette(palette12);
        lbSldivy = new QLabel(grafico);
        lbSldivy->setObjectName(QStringLiteral("lbSldivy"));
        lbSldivy->setGeometry(QRect(467, 15, 41, 21));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush);
        lbSldivy->setPalette(palette13);
        Sldivy = new QSlider(grafico);
        Sldivy->setObjectName(QStringLiteral("Sldivy"));
        Sldivy->setEnabled(true);
        Sldivy->setGeometry(QRect(477, 40, 20, 391));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush5);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush5);
        Sldivy->setPalette(palette14);
        Sldivy->setFocusPolicy(Qt::StrongFocus);
        Sldivy->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        Sldivy->setMaximum(60);
        Sldivy->setSingleStep(1);
        Sldivy->setPageStep(10);
        Sldivy->setValue(5);
        Sldivy->setSliderPosition(5);
        Sldivy->setOrientation(Qt::Vertical);
        Sldivy->setInvertedAppearance(false);
        Sldivy->setInvertedControls(false);
        Sldivy->setTickPosition(QSlider::NoTicks);
        gbondas = new QGroupBox(grafico);
        gbondas->setObjectName(QStringLiteral("gbondas"));
        gbondas->setGeometry(QRect(240, 70, 106, 361));
        verticalLayoutWidget = new QWidget(gbondas);
        verticalLayoutWidget->setObjectName(QStringLiteral("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(4, 20, 101, 341));
        verticalLayout = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        pBond_3 = new QPushButton(verticalLayoutWidget);
        pBond_3->setObjectName(QStringLiteral("pBond_3"));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBond_3->setPalette(palette15);
        pBond_3->setAutoFillBackground(false);
        pBond_3->setIcon(icon);
        pBond_3->setIconSize(QSize(70, 60));
        pBond_3->setFlat(true);

        verticalLayout->addWidget(pBond_3);

        pBond_4 = new QPushButton(verticalLayoutWidget);
        pBond_4->setObjectName(QStringLiteral("pBond_4"));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBond_4->setPalette(palette16);
        pBond_4->setAutoFillBackground(false);
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/cuadrada.png"), QSize(), QIcon::Normal, QIcon::Off);
        pBond_4->setIcon(icon2);
        pBond_4->setIconSize(QSize(70, 60));
        pBond_4->setFlat(true);

        verticalLayout->addWidget(pBond_4);

        pBond_2 = new QPushButton(verticalLayoutWidget);
        pBond_2->setObjectName(QStringLiteral("pBond_2"));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush);
        palette17.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBond_2->setPalette(palette17);
        pBond_2->setAutoFillBackground(false);
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/triangular.png"), QSize(), QIcon::Normal, QIcon::Off);
        pBond_2->setIcon(icon3);
        pBond_2->setIconSize(QSize(70, 60));
        pBond_2->setFlat(true);

        verticalLayout->addWidget(pBond_2);

        pBond_5 = new QPushButton(verticalLayoutWidget);
        pBond_5->setObjectName(QStringLiteral("pBond_5"));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush);
        palette18.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette18.setBrush(QPalette::Active, QPalette::Text, brush3);
        palette18.setBrush(QPalette::Active, QPalette::ButtonText, brush3);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::Text, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::ButtonText, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette18.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush);
        pBond_5->setPalette(palette18);
        pBond_5->setAutoFillBackground(false);
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/arb.png"), QSize(), QIcon::Normal, QIcon::Off);
        pBond_5->setIcon(icon4);
        pBond_5->setIconSize(QSize(70, 60));
        pBond_5->setFlat(true);

        verticalLayout->addWidget(pBond_5);

        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-2, 434, 611, 46));
        label->setAutoFillBackground(false);
        label->setStyleSheet(QStringLiteral("background: rgb(70,0,0)"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(241, 433, 106, 46));
        MainWindow->setCentralWidget(centralWidget);
        label->raise();
        label_2->raise();
        line->raise();
        line_4->raise();
        line_5->raise();
        line_6->raise();
        line_7->raise();
        line_8->raise();
        pBVpp->raise();
        pBfreq->raise();
        pBond->raise();
        pBdivX->raise();
        pBdivY->raise();
        pBopc->raise();
        grafico->raise();

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        pBVpp->setText(QApplication::translate("MainWindow", "Vpp = \n"
"Offset = ", nullptr));
        pBfreq->setText(QApplication::translate("MainWindow", "Freq = ", nullptr));
        pBond->setText(QString());
        pBdivX->setText(QApplication::translate("MainWindow", "10 ms/div", nullptr));
        pBdivY->setText(QApplication::translate("MainWindow", "5 V/div", nullptr));
        pBopc->setText(QString());
        lbSlVpp->setText(QApplication::translate("MainWindow", "Vpp", nullptr));
        lbSloffset->setText(QApplication::translate("MainWindow", "Offset", nullptr));
        lbSlFreq->setText(QApplication::translate("MainWindow", "Frecuencia", nullptr));
        lbSldivx->setText(QApplication::translate("MainWindow", "Div T", nullptr));
        lbSldivy->setText(QApplication::translate("MainWindow", "Div V", nullptr));
        gbondas->setTitle(QString());
        pBond_3->setText(QString());
        pBond_4->setText(QString());
        pBond_2->setText(QString());
        pBond_5->setText(QString());
        label->setText(QString());
        label_2->setText(QApplication::translate("MainWindow", "TextLabel", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
